baseurl = "/"
title = "Office 365 blog"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
googleAnalytics = "UA-61454000-4" # Optional
disqusShortname = "o365blog-com"
pygmentsuseclasses = true
publishDir = "docs"

[Author] # Used in authorbox
    name = "Dr Nestori Syynimaa"
    bio = "Dr Syynimaa is a senior Office 365 consultant and in [**Sovelto Plc**](http://www.sovelto.fi). He is MCT and holds several Microsoft certifications including MCSA Office 365. He is also a university teacher in [**University of Jyväskylä**](http://www.jyu.fi)."
    avatar = "images/nestori.jpg"

[Params]
    subtitle = "Your source for Office 365 administering" # Subtitle of your site. Used in site header
    description = "The site for all Office 365 administrators" # Description of your site. Used in meta description
    opengraph = true # Enable OpenGraph if true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true # Show authorbox at bottom of pages if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    social_twitter = "NestoriSyynimaa"
    social_linkedin = "nestori"
    social_email = "nestori.syynimaa@gerenios.com"

